from __future__ import annotations

from ..core.models import ScanReport


def render_markdown(report: ScanReport) -> str:
    lines: list[str] = []
    lines.append(f"# AuditSec Training Report (OWASP Top 10)\n")
    lines.append(f"- Target: {report.target.base_url}")
    lines.append(f"- Started: {report.started_at}")
    lines.append(f"- Finished: {report.finished_at}\n")

    if not report.findings:
        lines.append("## Findings\n")
        lines.append("No findings detected by the passive checks enabled in this simulator.")
        return "\n".join(lines) + "\n"

    # Simple priority ordering
    order = {"high": 0, "medium": 1, "low": 2, "informational": 3}
    findings = sorted(report.findings, key=lambda f: order.get(f.severity, 9))

    lines.append("## Findings\n")
    for f in findings:
        lines.append(f"### [{f.severity.upper()}] {f.title}")
        lines.append(f"- ID: {f.id}")
        lines.append(f"- OWASP: {f.owasp_category}")
        lines.append(f"- Description: {f.description}")
        if f.evidence:
            lines.append("- Evidence:")
            for k, v in f.evidence.items():
                lines.append(f"  - {k}: {v}")
        if f.recommendation:
            lines.append(f"- Recommendation: {f.recommendation}")
        if f.references:
            lines.append("- References:")
            for r in f.references:
                lines.append(f"  - {r}")
        lines.append("")

    lines.append("## Notes\n")
    lines.append(
        "This report is generated by a **non-offensive** educational simulator. It does not attempt exploitation or bypass techniques. "
        "Use it to guide hardening and secure development practices."
    )

    return "\n".join(lines) + "\n"
